[project]
name = "retryme"
version = "0.1.0"
description = "Tiny retry decorator for Python"
authors = [{ name="veliqq" }]
readme = "README.md"
requires-python = ">=3.8"
license = { text="MIT" }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
